#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FW_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_FILE="$FW_DIR/builder_config.local.h"

: "${BUILDER_WIFI_SSID:=}"
: "${BUILDER_WIFI_PASSWORD:=}"
: "${DEVICE_SETUP_CODE:=}"
: "${BUILD_PROFILE:=1}"

if [[ -z "$BUILDER_WIFI_SSID" ]]; then
  echo "BUILDER_WIFI_SSID is required"
  exit 1
fi

if [[ -z "$DEVICE_SETUP_CODE" ]]; then
  echo "DEVICE_SETUP_CODE is required"
  exit 1
fi

cat > "$OUT_FILE" <<CONFIG
#pragma once

// Generated by tools/generate_builder_config.sh
#define BUILD_PROFILE ${BUILD_PROFILE}
#define BUILDER_WIFI_SSID "${BUILDER_WIFI_SSID}"
#define BUILDER_WIFI_PASSWORD "${BUILDER_WIFI_PASSWORD}"
#define DEVICE_SETUP_CODE_VALUE "${DEVICE_SETUP_CODE}"

// Optional tuning values.
#define AP_MODE_TIMEOUT_MS 600000UL
#define RESET_HOLD_MS 4000UL
#define WIFI_CONNECT_CYCLES_BEFORE_AP 3
#define WIFI_CONNECT_ATTEMPTS_PER_CYCLE 20
#define WIFI_RECONNECT_INTERVAL_MS 5000UL
#define WIFI_FAILS_BEFORE_AP 3
CONFIG

echo "Generated $OUT_FILE"
